/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Legacy Marketing Campaigns Contacts API
* The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ExportRecipientRequest struct for ExportRecipientRequest
type ExportRecipientRequest struct {
	// IDs of the recipient lists you want to export.
	ListIds *[]int32 `json:"list_ids,omitempty"`
	// IDs of the recipient segments you want to export.
	SegmentIds    *[]int32                             `json:"segment_ids,omitempty"`
	Notifications *ExportRecipientRequestNotifications `json:"notifications,omitempty"`
	// File type for export file. Choose from `json` or `csv`.
	FileType *FileType `json:"file_type,omitempty"`
	// The maximum size of an export file in MB. Note that when this option is specified, multiple output files may be returned from the export.
	MaxFileSize *int32 `json:"max_file_size,omitempty"`
}
