/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Legacy Marketing Campaigns Contacts API
* The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ContactdbRecipient200RecipientsInner struct for ContactdbRecipient200RecipientsInner
type ContactdbRecipient200RecipientsInner struct {
	// The ID of this recipient.
	Id *string `json:"id,omitempty"`
	// The time this record was created in your contactdb, in unixtime.
	CreatedAt *float32 `json:"created_at,omitempty"`
	// The custom fields assigned to this recipient and their values.
	CustomFields *[]ContactdbCustomFieldIdValue `json:"custom_fields,omitempty"`
	// The email address of this recipient. This is a default custom field that SendGrid provides.
	Email string `json:"email"`
	// The first name of this recipient. This is a default custom field that SendGrid provides.
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the recipient.
	LastName *string `json:"last_name,omitempty"`
	// The last time this recipient clicked a link from one of your campaigns, in unixtime.
	LastClicked *float32 `json:"last_clicked,omitempty"`
	// The last time this user was emailed by one of your campaigns, in unixtime.
	LastEmailed *float32 `json:"last_emailed,omitempty"`
	// The last time this recipient opened an email from you, in unixtime.
	LastOpened *float32 `json:"last_opened,omitempty"`
	// The last update date for this recipient's record.
	UpdatedAt *float32 `json:"updated_at,omitempty"`
}
