/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Legacy Marketing Campaigns Contacts API
* The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// Metadata struct for Metadata
type Metadata struct {
	// The URL of the previous page of results. If this field isn't present, you're at the start of the list.
	Prev *string `json:"prev,omitempty"`
	// The URL of the current page of results.
	Self *string `json:"self,omitempty"`
	// The URL of the next page of results. If this field isn't present, you're at the end of the list.
	Next *string `json:"next,omitempty"`
	// The number of items in the entire list, i.e., across all pages.
	Count *float32 `json:"count,omitempty"`
}
