/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Legacy Marketing Campaigns Contacts API
* The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// RecipientExport struct for RecipientExport
type RecipientExport struct {
	Id string `json:"id"`
	// The export job's status. Allowed values: `pending`, `ready`, or `failure`.
	Status Status `json:"status"`
	// The ISO8601 timestamp when the export was begun.
	CreatedAt string `json:"created_at"`
	// The ISO8601 timestamp when the export was updated.
	UpdatedAt string `json:"updated_at"`
	// The ISO8601 timestamp when the export was completed.
	CompletedAt *string `json:"completed_at,omitempty"`
	// The ISO8601 timestamp when the exported file on S3 will expire.
	ExpiresAt string `json:"expires_at"`
	// One or more download URLs for the recipient file if the status is `ready`.
	Urls *[]string `json:"urls,omitempty"`
	// A human readable message if the status is `failure`.
	Message  *string   `json:"message,omitempty"`
	Metadata *Metadata `json:"_metadata,omitempty"`
	// The total number of exported recipients.
	RecipientCount *int32 `json:"recipient_count,omitempty"`
}
