/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Teammates API
* The Twilio SendGrid Teammates API allows you to add, manage, and remove Teammates, or user accounts, from your SendGrid account. Teammates function like user accounts on the SendGrid account, allowing you to invite additional users to your account with scoped access. You can think of Teammates as SendGrid's approach to enabling [role-based access control](https://en.wikipedia.org/wiki/Role-based_access_control) for your SendGrid account. For even more control over the access to your account, see the [Twilio SendGrid SSO API](https://docs.sendgrid.com/api-reference/single-sign-on-teammates/), which enables SSO-authenticated Teammates to be managed through a SAML 2.0 identity provider.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// InviteTeammate201Response struct for InviteTeammate201Response
type InviteTeammate201Response struct {
	// Token to identify invite
	Token *string `json:"token,omitempty"`
	// Teammate's email address
	Email *string `json:"email,omitempty"`
	// Initial set of permissions to give to teammate if they accept the invite
	Scopes *[]interface{} `json:"scopes,omitempty"`
	// Set to true if teammate should have admin privileges
	IsAdmin *bool `json:"is_admin,omitempty"`
}
