/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Teammates API
* The Twilio SendGrid Teammates API allows you to add, manage, and remove Teammates, or user accounts, from your SendGrid account. Teammates function like user accounts on the SendGrid account, allowing you to invite additional users to your account with scoped access. You can think of Teammates as SendGrid's approach to enabling [role-based access control](https://en.wikipedia.org/wiki/Role-based_access_control) for your SendGrid account. For even more control over the access to your account, see the [Twilio SendGrid SSO API](https://docs.sendgrid.com/api-reference/single-sign-on-teammates/), which enables SSO-authenticated Teammates to be managed through a SAML 2.0 identity provider.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ListSubuserByTemplate200ResponseSubuserAccessInner An array of Subusers to which the Teammate has access.
type ListSubuserByTemplate200ResponseSubuserAccessInner struct {
	// The ID of a Subuser to which the Teammate has access. You can retrieve Subuser IDs from the [Subusers API](https://docs.sendgrid.com/api-reference/subusers-api/).
	Id *int32 `json:"id,omitempty"`
	// The username of a Subuser to which the Teammate has access.
	Username *string `json:"username,omitempty"`
	// The email address of a Subuser to which the Teammate has access.
	Email *string `json:"email,omitempty"`
	// Indicates if the Subuser is active for the SendGrid account.
	Disabled *bool `json:"disabled,omitempty"`
	// The level of access the Teammate has to the specified Subuser. This property value may be either `admin` or `restricted`. When is property is set to `restricted`, the Teammate has only the permissions assigned in the `scopes` property.
	PermissionType *PermissionType `json:"permission_type,omitempty"`
	// The permissions or scopes that the Teammate can access on behalf of the Subuser. See [**Teammate Permissions**](https://docs.sendgrid.com/ui/account-and-settings/teammate-permissions) for a complete list of available scopes.
	Scopes *[]string `json:"scopes,omitempty"`
}
