/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Link Branding API
* The Twilio SendGrid Link Branding API allows you to configure your domain settings so that all of the click-tracked links, opens, and images in your emails are served from your domain rather than `sendgrid.net`. Spam filters and recipient servers look at the links within emails to determine whether the email appear trustworthy. They use the reputation of the root domain to determine whether the links can be trusted.  You can also manage Link Branding in the **Sender Authentication** section of the Twilio SendGrid application user interface.   See [**How to Set Up Link Branding**](https: //sendgrid.com/docs/ui/account-and-settings/how-to-set-up-link-branding/) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// LinkBranding200DnsOwnerCname The DNS record generated to verify who created the link branding.
type LinkBranding200DnsOwnerCname struct {
	// Indicates if the DNS record is valid.
	Valid Valid5 `json:"valid"`
	// The type of DNS record generated.
	Type *Type1 `json:"type,omitempty"`
	// Used to verify the link branding. The subdomain of this domain is the ID of the user who created the link branding.
	Host string `json:"host"`
	// The domain that the DNS record points to.
	Data string `json:"data"`
}
