/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Domain Authentication API
* The Twilio SendGrid Domain Authentication API allows you to manage your authenticated domains and their settings.  Domain Authentication is a required step when setting up your Twilio SendGrid account because it's essential to ensuring the deliverability of your email. Domain Authentication signals trustworthiness to email inbox providers and your recipients by approving SendGrid to send email on behalf of your domain. For more information, see [**How to Set Up Domain Authentication**](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/).  Each user may have a maximum of 3,000 authenticated domains and 3,000 link brandings. This limit is at the user level, meaning each Subuser belonging to a parent account may have its own 3,000 authenticated domains and 3,000 link brandings.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// AuthenticatedDomainSpfDnsMailServer Designates which mail server is responsible for accepting messages from a domain.
type AuthenticatedDomainSpfDnsMailServer struct {
	// The domain sending the messages.
	Host string `json:"host"`
	// They type of DNS record.
	Type string `json:"type"`
	// The mail server responsible for accepting messages from the sending domain.
	Data string `json:"data"`
	// Indicates if this is a valid DNS record.
	Valid bool `json:"valid"`
}
