/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid IP Address Management API
* The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// GetIpPool200Response struct for GetIpPool200Response
type GetIpPool200Response struct {
	// The name of the IP Pool.
	Name *string `json:"name,omitempty"`
	// The unique ID of the IP Pool.
	Id *string `json:"id,omitempty"`
	// A sample list of IP addresses associated with the IP Pool. The sample is limited to 10 results.
	IpsPreview *[]string `json:"ips_preview,omitempty"`
	// The total number of IP addresses in the IP Pool. An IP Pool can have a maximum of 100 associated IP addresses.
	TotalIpCount *int32 `json:"total_ip_count,omitempty"`
	// The total number of IP addresses by region. this object is only returned if the `include_region` parameter is included and set to `true` in the API request.
	IpCountByRegion *[]GetIpPool200ResponseIpCountByRegionInner `json:"ip_count_by_region,omitempty"`
}
