/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid IP Address Management API
* The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ListSubUserAssignedToIp200ResponseMetadataNextParams A collection of fields that can be used to work the endpoint.
type ListSubUserAssignedToIp200ResponseMetadataNextParams struct {
	// Specifies which items to be returned by the API. When the `after_key` is specified, the API will return items beginning from the first item after the item specified. This parameter can be used in combination with `limit` to iterate through paginated results. The `after_key` cannot be used in combination with the `before_key` parameter.
	AfterKey *string `json:"after_key,omitempty"`
	// The `limit` specified in the request. This parameter will be included only if it was specified in the request. This is not the default limit enforced by the API.
	Limit *string `json:"limit,omitempty"`
}
