/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid IP Address Management API
* The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// CreateIpPoolRequest struct for CreateIpPoolRequest
type CreateIpPoolRequest struct {
	// The name to assign to the IP Pool. An IP Pool name cannot begin with a space or period.
	Name string `json:"name"`
	// An array of IP addresses to assign to the IP Pool. All assignments must succeed.
	Ips *[]string `json:"ips,omitempty"`
}
