/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid IP Address Management API
* The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// AddIpRequest struct for AddIpRequest
type AddIpRequest struct {
	// Indicates if the IP address is set to automatically [warmup](https://docs.sendgrid.com/ui/sending-email/warming-up-an-ip-address).
	IsAutoWarmup bool `json:"is_auto_warmup"`
	// Indicates if a parent on the account is able to send email from the IP address.
	IsParentAssigned bool `json:"is_parent_assigned"`
	// An array of Subuser IDs the IP address will be assigned to.
	Subusers *[]string `json:"subusers,omitempty"`
	// The region to which the IP address is assigned. This property will only be returned if the `include_region` query parameter is included and set to `true` as part of the API request.
	Region *Region3 `json:"region,omitempty"`
	// Boolean indicating whether or not to return the IP address's region information in the response.
	IncludeRegion *bool `json:"include_region,omitempty"`
}
