/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Webhook Configuration API
* The Twilio SendGrid Webhooks API allows you to configure the Event and Parse Webhooks.  Email is a data-rich channel, and implementing the Event Webhook will allow you to consume those data in nearly real time. This means you can actively monitor and participate in the health of your email program throughout the send cycle.  The Inbound Parse Webhook processes all incoming email for a domain or subdomain, parses the contents and attachments and then POSTs `multipart/form-data` to a URL that you choose.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// CreateEventWebhook400ResponseErrorsInner struct for CreateEventWebhook400ResponseErrorsInner
type CreateEventWebhook400ResponseErrorsInner struct {
	// The ID of a Webhook that exists on your account that is already configured to send events to the endpoint URL you provided.
	Id *string `json:"id,omitempty"`
	// Error message.
	Message *string `json:"message,omitempty"`
	// The URL that is already configured as a Webhook endpoint for one of your existing Webhooks.
	Url *string `json:"url,omitempty"`
}
