/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Webhook Configuration API
* The Twilio SendGrid Webhooks API allows you to configure the Event and Parse Webhooks.  Email is a data-rich channel, and implementing the Event Webhook will allow you to consume those data in nearly real time. This means you can actively monitor and participate in the health of your email program throughout the send cycle.  The Inbound Parse Webhook processes all incoming email for a domain or subdomain, parses the contents and attachments and then POSTs `multipart/form-data` to a URL that you choose.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// EventWebhookOauthResponseProps struct for EventWebhookOauthResponseProps
type EventWebhookOauthResponseProps struct {
	// The OAuth client ID SendGrid sends to your OAuth server or service provider to generate an OAuth access token.
	OauthClientId *string `json:"oauth_client_id,omitempty"`
	// The URL where SendGrid sends the OAuth client ID and client secret to generate an access token. This should be your OAuth server or service provider.
	OauthTokenUrl *string `json:"oauth_token_url,omitempty"`
}
