/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Alerts API
* The Twilio SendGrid Alerts API allows you to specify an email address to receive notifications regarding your email usage or statistics. You can set up alerts to be sent to a specific email address on a recurring basis, whether for informational purposes or when specific account actions occur.  For most alerts, you can choose to have the alert sent to you as needed, hourly, daily, weekly, or monthly. The information contained in your alert will be for the last period of the alert. For example, if you choose weekly for the statistics alert, you will receive the statistics for the last week.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ListAlert200ResponseInner struct for ListAlert200ResponseInner
type ListAlert200ResponseInner struct {
	// A Unix timestamp indicating when the alert was created.
	CreatedAt int32 `json:"created_at"`
	// The email address that the alert will be sent to.
	EmailTo string `json:"email_to"`
	// The ID of the alert.
	Id int32 `json:"id"`
	// If the alert is of type usage_limit, this indicates the percentage of email usage that must be reached before the alert will be sent.
	Percentage *int32 `json:"percentage,omitempty"`
	// The type of alert.
	Type Type1 `json:"type"`
	// A Unix timestamp indicating when the alert was last modified.
	UpdatedAt *int32 `json:"updated_at,omitempty"`
	// If the alert is of type stats_notification, this indicates how frequently the stats notifications will be sent. For example, \"daily\", \"weekly\", or \"monthly\".
	Frequency *string `json:"frequency,omitempty"`
}
