/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Marketing Campaigns Contacts API
* The Twilio SendGrid Marketing Campaigns Contacts API allows you to manage all of your marketing contacts programmatically. You can also import and export contacts using this API. The Contacts API allows you to associate contacts with lists and segments; however, to manage the lists and segments themselves, see the [Lists API](https://docs.sendgrid.com/api-reference/lists/) and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/).  You can also manage your marketing contacts with the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). See [**How to Send Email with New Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// ImportContact200Response struct for ImportContact200Response
type ImportContact200Response struct {
	// The ID of the import job.
	JobId *string `json:"job_id,omitempty"`
	// The URI to PUT the upload file to.
	UploadUri *string `json:"upload_uri,omitempty"`
	// A list of headers that must be included in PUT request.
	UploadHeaders *[]ImportContact200ResponseUploadHeadersInner `json:"upload_headers,omitempty"`
}
