/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Integrations API
* Integrations allows you to connect your SendGrid applications with third-party services and forward SendGrid email events to those external applications. Currently, Integrations supports event forwarding to [Segment](https://segment.com/docs). You can use this API to create, delete, view, and update your Integrations.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// DestinationRegion2 the model 'DestinationRegion2'
type DestinationRegion2 string

// List of DestinationRegion2
const (
	DESTINATIONREGION2_EU DestinationRegion2 = "EU"
	DESTINATIONREGION2_US DestinationRegion2 = "US"
)
