/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Integrations API
* Integrations allows you to connect your SendGrid applications with third-party services and forward SendGrid email events to those external applications. Currently, Integrations supports event forwarding to [Segment](https://segment.com/docs). You can use this API to create, delete, view, and update your Integrations.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// IntegrationInput struct for IntegrationInput
type IntegrationInput struct {
	// The third-party application you would like to forward your events to.
	Destination Destination2               `json:"destination"`
	Filters     IntegrationInputFilters    `json:"filters"`
	Properties  IntegrationInputProperties `json:"properties"`
	// The nickname for the Integration.
	Label *string `json:"label,omitempty"`
}
