/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Statistics API
* The Twilio SendGrid Statistics API allows you to retrieve the various statistics related to your email program.  Tracking your emails is an important part of being a good sender and learning about how your users interact with your email. This includes everything from clicks and opens to looking at which browsers and mailbox providers your customers use.  SendGrid has broken up statistics in specific ways so that you can get at-a-glance data, as well as the details of how your email is being used.  Category statistics are available for the previous thirteen months only.  See [**Statistics Overview**](https://docs.sendgrid.com/ui/analytics-and-reporting/stats-overview) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// AdvancedStatsMailboxProvider The individual events and their stats.
type AdvancedStatsMailboxProvider struct {
	// The number of emails that were not allowed to be delivered by ISPs.
	Blocks *int32 `json:"blocks,omitempty"`
	// The number of emails that bounced instead of being delivered.
	Bounces *int32 `json:"bounces,omitempty"`
	// The number of emails that temporarily could not be delivered.
	Deferred *int32 `json:"deferred,omitempty"`
	// The number of emails SendGrid was able to confirm were actually delivered to a recipient.
	Delivered *int32 `json:"delivered,omitempty"`
	// The number of emails that were not delivered due to the recipient email address being on a suppression list.
	Drops *int32 `json:"drops,omitempty"`
	// The number of emails that were requested to be delivered.
	Requests *int32 `json:"requests,omitempty"`
	// Requests from your website, application, or mail client via SMTP Relay or the Web API that SendGrid processed.
	Processed *int32 `json:"processed,omitempty"`
	// The number of recipients who marked your email as spam.
	SpamReports *int32 `json:"spam_reports,omitempty"`
}
