/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Statistics API
* The Twilio SendGrid Statistics API allows you to retrieve the various statistics related to your email program.  Tracking your emails is an important part of being a good sender and learning about how your users interact with your email. This includes everything from clicks and opens to looking at which browsers and mailbox providers your customers use.  SendGrid has broken up statistics in specific ways so that you can get at-a-glance data, as well as the details of how your email is being used.  Category statistics are available for the previous thirteen months only.  See [**Statistics Overview**](https://docs.sendgrid.com/ui/analytics-and-reporting/stats-overview) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// CategoryStatsStatsInnerMetrics struct for CategoryStatsStatsInnerMetrics
type CategoryStatsStatsInnerMetrics struct {
	// The number of emails that were not allowed to be delivered by ISPs.
	Blocks int32 `json:"blocks"`
	// The number of emails that were dropped because of a bounce.
	BounceDrops int32 `json:"bounce_drops"`
	// The number of emails that bounced instead of being delivered.
	Bounces int32 `json:"bounces"`
	// The number of links that were clicked.
	Clicks int32 `json:"clicks"`
	// The number of emails that temporarily could not be delivered.
	Deferred int32 `json:"deferred"`
	// The number of emails SendGrid was able to confirm were actually delivered to a recipient.
	Delivered int32 `json:"delivered"`
	// The number of recipients who had malformed email addresses or whose mail provider reported the address as invalid.
	InvalidEmails int32 `json:"invalid_emails"`
	// The total number of times your emails were opened by recipients.
	Opens int32 `json:"opens"`
	// Requests from your website, application, or mail client via SMTP Relay or the API that SendGrid processed.
	Processed int32 `json:"processed"`
	// The number of emails that were requested to be delivered.
	Requests int32 `json:"requests"`
	// The number of emails that were dropped due to a recipient previously marking your emails as spam.
	SpamReportDrops int32 `json:"spam_report_drops"`
	// The number of recipients who marked your email as spam.
	SpamReports int32 `json:"spam_reports"`
	// The number of unique recipients who clicked links in your emails.
	UniqueClicks int32 `json:"unique_clicks"`
	// The number of unique recipients who opened your emails.
	UniqueOpens int32 `json:"unique_opens"`
	// The number of emails dropped due to a recipient unsubscribing from your emails.
	UnsubscribeDrops int32 `json:"unsubscribe_drops"`
	// The number of recipients who unsubscribed from your emails.
	Unsubscribes int32 `json:"unsubscribes"`
}
