/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Verified Senders API
* The Twilio SendGrid Verified Senders API allows you to programmatically manage the Sender Identities that are authorized to send email for your account. You can also manage Sender Identities in the [SendGrid application user interface](https://app.sendgrid.com/settings/sender_auth). See [**Single Sender Verification**](https://sendgrid.com/docs/ui/sending-email/sender-verification/) for more information.  You an use this API to create new Sender Identities, retrieve a list of existing Sender Identities, check the status of a Sender Identity, update a Sender Identity, and delete a Sender Identity.  This API offers additional operations to check for domains known to implement DMARC and resend verification emails to Sender Identities that have yet to complete the verification process.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// VerifiedSenderResponse struct for VerifiedSenderResponse
type VerifiedSenderResponse struct {
	Id          *int32  `json:"id,omitempty"`
	Nickname    *string `json:"nickname,omitempty"`
	FromEmail   *string `json:"from_email,omitempty"`
	FromName    *string `json:"from_name,omitempty"`
	ReplyTo     *string `json:"reply_to,omitempty"`
	ReplyToName *string `json:"reply_to_name,omitempty"`
	Address     *string `json:"address,omitempty"`
	Address2    *string `json:"address2,omitempty"`
	State       *string `json:"state,omitempty"`
	City        *string `json:"city,omitempty"`
	Zip         *string `json:"zip,omitempty"`
	Country     *string `json:"country,omitempty"`
	Verified    *bool   `json:"verified,omitempty"`
	Locked      *bool   `json:"locked,omitempty"`
}
