/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Mail API
* The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// SendMailRequestContentInner struct for SendMailRequestContentInner
type SendMailRequestContentInner struct {
	// The MIME type of the content assigned in the `value` property of this object (e.g., `text/plain` or `text/html`).
	Type string `json:"type"`
	// The content of your message in the specified MIME type assigned in the `type` property of this object.
	Value string `json:"value"`
}
