/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Mail API
* The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// SendMailRequestTrackingSettingsClickTracking Allows you to track if a recipient clicked a link in your email.
type SendMailRequestTrackingSettingsClickTracking struct {
	// Indicates if this setting is enabled.
	Enable *bool `json:"enable,omitempty"`
	// Indicates if this setting should be included in the `text/plain` portion of your email.
	EnableText *bool `json:"enable_text,omitempty"`
}
