/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Mail API
* The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// SendMailRequestTrackingSettingsGanalytics Allows you to enable tracking provided by Google Analytics. See [**Google Analytics and SendGrid Statistics**](https://docs.sendgrid.com/ui/analytics-and-reporting/google-analytics) for more information about this property.
type SendMailRequestTrackingSettingsGanalytics struct {
	// Indicates if this setting is enabled.
	Enable *bool `json:"enable,omitempty"`
	// Name of the referrer source. (e.g., Google, SomeDomain.com, or Marketing Email)
	UtmSource *string `json:"utm_source,omitempty"`
	// Name of the marketing medium. (e.g., Email)
	UtmMedium *string `json:"utm_medium,omitempty"`
	// Used to identify any paid keywords.
	UtmTerm *string `json:"utm_term,omitempty"`
	// Used to differentiate your campaign from advertisements.
	UtmContent *string `json:"utm_content,omitempty"`
	// The name of the campaign.
	UtmCampaign *string `json:"utm_campaign,omitempty"`
}
