/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Email Activity API
* The Twilio SendGrid Email Activity API allows you to query all of your stored messages, query individual messages, and download a CSV with data about the stored messages. Once retrieved, you can inspect the data associated with your messages to better understand your mail send. For example, you may retrieve all bounced messages or all messages with the same subject line and search for commonalities among them.  You must [purchase additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity) to gain access to the Email Activity Feed API.  See **Getting Started with the Email Activity Feed API** for help building queries and working with this API. You can also work with email activity in the **Activity** section of the [Twilio SendGrid application user interface](https://app.sendgrid.com/email_activity).
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// Message struct for Message
type Message struct {
	// The 'From' email address used to deliver the message. This address should be a verified sender in your Twilio SendGrid account.
	FromEmail *string `json:"from_email,omitempty"`
	// A unique ID assigned to the message. This ID can be used to retrieve activity data for the specific message.
	MsgId *string `json:"msg_id,omitempty"`
	// The email's subject line.
	Subject *string `json:"subject,omitempty"`
	// The intended recipient's email address.
	ToEmail *string `json:"to_email,omitempty"`
	// The message's status.
	Status *Status3 `json:"status,omitempty"`
	// The ID associated with a Twilio SendGrid email template used to format the message.
	TemplateId string `json:"template_id"`
	// The unsubscribe group associated with this email.
	AsmGroupId int32 `json:"asm_group_id"`
	// Teammate's username
	Teammate string `json:"teammate"`
	// The ID of the API Key used to authenticate the sending request for the message.
	ApiKeyId string `json:"api_key_id"`
	// List of events related to email message
	Events []Event `json:"events"`
	// This is the IP of the user who sent the message.
	OriginatingIp string `json:"originating_ip"`
	// Categories users associated to the message
	Categories []string `json:"categories"`
	// JSON hash of key-value pairs associated with the message.
	UniqueArgs string `json:"unique_args"`
	// IP used to send to the remote Mail Transfer Agent.
	OutboundIp string `json:"outbound_ip"`
	// Whether or not the outbound IP is dedicated vs shared
	OutboundIpType OutboundIpType `json:"outbound_ip_type"`
}
