/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Subusers
* The Twilio SendGrid Subusers API allows you to create and manage your Subuser accounts. Subusers are available on [Pro and Premier plans](https://sendgrid.com/pricing), and you can think of them as sub-accounts. Each Subuser can have its own sending domains, IP addresses, and reporting. SendGrid recommends creating Subusers for each of the different types of emails you send—one Subuser for transactional emails and another for marketing emails. Independent Software Vendor (ISV) customers may also create Subusers for each of their customers.  You can also manage Subusers in the [Twilio SendGrid application user interface](https://app.sendgrid.com/settings/subusers). See [**Subusers**](https://docs.sendgrid.com/ui/account-and-settings/subusers) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// CategoryStatsStatsInnerMetrics struct for CategoryStatsStatsInnerMetrics
type CategoryStatsStatsInnerMetrics struct {
	// The number of emails that were not allowed to be delivered by ISPs.
	Blocks int32 `json:"blocks"`
	// The number of emails that were dropped because of a bounce.
	BounceDrops int32 `json:"bounce_drops"`
	// The number of emails that bounced instead of being delivered.
	Bounces int32 `json:"bounces"`
	// The number of links that were clicked.
	Clicks int32 `json:"clicks"`
	// The number of emails that temporarily could not be delivered.
	Deferred int32 `json:"deferred"`
	// The number of emails SendGrid was able to confirm were actually delivered to a recipient.
	Delivered int32 `json:"delivered"`
	// The number of recipients who had malformed email addresses or whose mail provider reported the address as invalid.
	InvalidEmails int32 `json:"invalid_emails"`
	// The total number of times your emails were opened by recipients.
	Opens int32 `json:"opens"`
	// Requests from your website, application, or mail client via SMTP Relay or the API that SendGrid processed.
	Processed int32 `json:"processed"`
	// The number of emails that were requested to be delivered.
	Requests int32 `json:"requests"`
	// The number of emails that were dropped due to a recipient previously marking your emails as spam.
	SpamReportDrops int32 `json:"spam_report_drops"`
	// The number of recipients who marked your email as spam.
	SpamReports int32 `json:"spam_reports"`
	// The number of unique recipients who clicked links in your emails.
	UniqueClicks int32 `json:"unique_clicks"`
	// The number of unique recipients who opened your emails.
	UniqueOpens int32 `json:"unique_opens"`
	// The number of emails dropped due to a recipient unsubscribing from your emails.
	UnsubscribeDrops int32 `json:"unsubscribe_drops"`
	// The number of recipients who unsubscribed from your emails.
	Unsubscribes int32 `json:"unsubscribes"`
}
