/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Subusers
* The Twilio SendGrid Subusers API allows you to create and manage your Subuser accounts. Subusers are available on [Pro and Premier plans](https://sendgrid.com/pricing), and you can think of them as sub-accounts. Each Subuser can have its own sending domains, IP addresses, and reporting. SendGrid recommends creating Subusers for each of the different types of emails you send—one Subuser for transactional emails and another for marketing emails. Independent Software Vendor (ISV) customers may also create Subusers for each of their customers.  You can also manage Subusers in the [Twilio SendGrid application user interface](https://app.sendgrid.com/settings/subusers). See [**Subusers**](https://docs.sendgrid.com/ui/account-and-settings/subusers) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// Subuser struct for Subuser
type Subuser struct {
	// Whether or not the user is enabled or disabled.
	Disabled bool `json:"disabled"`
	// The ID of this subuser.
	Id float32 `json:"id"`
	// The name by which this subuser will be referred.
	Username string `json:"username"`
	// The email address to contact this subuser.
	Email string `json:"email"`
	// The region this Subuser is assigned to. This property is returned only if the `include_region` parameter was included and set to `true` in the API request.
	Region *Region2 `json:"region,omitempty"`
}
