/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Subusers
* The Twilio SendGrid Subusers API allows you to create and manage your Subuser accounts. Subusers are available on [Pro and Premier plans](https://sendgrid.com/pricing), and you can think of them as sub-accounts. Each Subuser can have its own sending domains, IP addresses, and reporting. SendGrid recommends creating Subusers for each of the different types of emails you send—one Subuser for transactional emails and another for marketing emails. Independent Software Vendor (ISV) customers may also create Subusers for each of their customers.  You can also manage Subusers in the [Twilio SendGrid application user interface](https://app.sendgrid.com/settings/subusers). See [**Subusers**](https://docs.sendgrid.com/ui/account-and-settings/subusers) for more information.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// SubuserStatsStatsInner struct for SubuserStatsStatsInner
type SubuserStatsStatsInner struct {
	// The first name of the subuser.
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the subuser.
	LastName *string                        `json:"last_name,omitempty"`
	Metrics  *SubuserStatsStatsInnerMetrics `json:"metrics,omitempty"`
	// The username of the subuser.
	Name *string `json:"name,omitempty"`
	// The type of account.
	Type *string `json:"type,omitempty"`
}
