/*
* This code was generated by
*
* SENDGRID-OAI-GENERATOR
*
* Twilio SendGrid Marketing Campaigns Designs
* The Twilio SendGrid Designs API offers the ability to manage assets stored in the Twilio SendGrid [Design Library](https://mc.sendgrid.com/design-library/my-designs).  The Design Library is a feature-rich email layout tool and media repository. You can [build designs for all your marketing email needs](https://sendgrid.com/docs/ui/sending-email/working-with-marketing-campaigns-email-designs/), including Single Sends and Automations.  You can also duplicate and then modify one of the pre-built designs provided by Twilio SendGrid to get you started.  The Designs API provides a REST-like interface for creating new designs, retrieving a list of existing designs, duplicating or updating a design, and deleting a design.
*
* NOTE: This class is auto generated by OpenAPI Generator.
* https://openapi-generator.tech
* Do not edit the class manually.
 */

package openapi

// DesignOutputSummary struct for DesignOutputSummary
type DesignOutputSummary struct {
	// ID of the Design.
	Id *string `json:"id,omitempty"`
	// Datetime that Design was last updated.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Datetime that Design was created.
	CreatedAt *string `json:"created_at,omitempty"`
	// A Thumbnail preview of the template's html content.
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
	// The name of the new design.
	Name *string `json:"name,omitempty"`
	// The editor used in the UI.
	Editor *Editor `json:"editor,omitempty"`
}
